#!/bin/bash -l
#SBATCH --job-name="my-job"
#SBATCH --time=00:30:00          # final intended time
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=debug       # final intended partition
#SBATCH --constraint=mc
#SBATCH --output="output.log"
#SBATCH --error="error.log"

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun hostname

