#!/bin/bash -l
#SBATCH --job-name="my-job"
#SBATCH --time=00:01:00
#SBATCH --time=00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-core=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=SELECT_PARTITION
#SBATCH --constraint=mc


#SBATCH --partition=
#SBATCH --partition=debug
#SBATCH --constraint=mc
#SBATCH --output="output.log"
#SBATCH --error="error.log"

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

srun hostname
